sudo: required
services:
  - docker

before_install:
  - docker build -t taylorj99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run taylorj99/react-test npm run test -- --coverage

after_success:
  - docker build -t taylorj99/harpnet-client ./client
  - docker build -t taylorj99/harpnet-nginx ./nginx
  - docker build -t taylorj99/harpnet-server ./server
  - docker build -t taylorj99/harpnet-postgres ./postgres
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push taylorj99/harpnet-client
  - docker push taylorj99/harpnet-nginx
  - docker push taylorj99/harpnet-server
  - docker push taylorj99/harpnet-postgres
