// Error constants
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Auth constants
export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_USER = "SET_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

// Profile constants
export const PROFILE_LOADING = "PROFILE_LOADING";
export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const RELOAD_PROFILE = "RELOAD_PROFILE";
export const RESET_PROFILE_RELOAD = "RESET_PROFILE_RELOAD";

export const SET_VIEW_PROFILE = "SET_VIEW_PROFILE";
export const RELOAD_VIEW_PROFILE = "RELOAD_VIEW_PROFILE";
export const CLEAR_VIEW_PROFILE = "CLEAR_VIEW_PROFILE";
export const END_VIEW_PROFILE_RELOAD = "END_VIEW_PROFILE_RELOAD";

// Follows constants
export const SET_FOLLOWS = "SET_FOLLOWS";
export const CLEAR_FOLLOWS = "CLEAR_FOLLOWS";
export const FOLLOWS_LOADING = "FOLLOWS_LOADING";
export const SET_FOLLOW_SUGGESTIONS = "SET_FOLLOW_SUGGESTIONS";
export const RELOAD_FOLLOW_SUGGESTIONS = "RELOAD_FOLLOW_SUGGESTIONS";

// Post constants
export const GET_POSTS = "SET_POSTS";
export const GET_COMMENTS = "GET_COMMENTS";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const RELOAD_FEED = "RELOAD_FEED";
export const FEED_LOADING = "FEED_LOADING";
export const SET_SINGLE_POST = "SET_SINGLE_POST";
export const RESET_SINGLE_POST = "RESET_SINGLE_POST";
export const RELOAD_SINGLE_POST = "RELOAD_SINGLE_POST";
export const END_RELOAD_SINGLE_POST = "END_RELOAD_SINGLE_POST";

// Search constants
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_COMPLETE = "SEARCH_COMPLETE";
export const RESET_SEARCH = "RESET_SEARCH";
export const RELOAD_SEARCH = "RELOAD_SEARCH";
