version: "3"
services:
  redis:
    image: redis

  postgres:
    build: ../postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres

  client:
    build: ../client
    volumes:
      - /app/node_modules
      - ../client:/app

  api:
    build: ../server
    volumes:
      - /app/node_modules
      - ../server:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    restart: always
    build: ../nginx
    ports:
      - "3050:80"
