version: "3"
services:
  redis:
    image: redis

  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ../postgres
    volumes:
      - ../postgres/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    volumes:
      - /app/node_modules
      - ../client:/app

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ../server
    volumes:
      - /app/node_modules
      - ../server:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ../nginx
    ports:
      - "3050:80"
